{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "fff17cf3-3ab0-4a6e-9178-e3a06dd1703d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No hay archivos en Landing.\n",
      "Proceso de ingesta finalizado.\n"
     ]
    }
   ],
   "source": [
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "import shutil\n",
    "import csv\n",
    "\n",
    "BASE_DIR = Path(__file__).resolve().parent.parent\n",
    "\n",
    "LANDING_DIR = BASE_DIR / \"Landing\"\n",
    "DATALAKE_DIR = BASE_DIR / \"DataLake\"\n",
    "RAW_CSV_DIR = DATALAKE_DIR / \"raw\" / \"csv\"\n",
    "RAW_EXCEL_DIR = DATALAKE_DIR / \"raw\" / \"excel\"\n",
    "RAW_JSON_DIR = DATALAKE_DIR / \"raw\" / \"json\"\n",
    "REJECTED_DIR = DATALAKE_DIR / \"rejected\"\n",
    "LOGS_DIR = BASE_DIR / \"logs\"\n",
    "LOG_FILE = LOGS_DIR / \"datalake_log.csv\"\n",
    "\n",
    "def escribir_log(nivel, proceso, archivo, accion, estado, detalle):\n",
    "    existe = LOG_FILE.exists()\n",
    "\n",
    "    with open(LOG_FILE, mode=\"a\", newline=\"\", encoding=\"utf-8-sig\") as f:\n",
    "        writer = csv.writer(f)\n",
    "\n",
    "        if not existe:\n",
    "            writer.writerow([\n",
    "                \"fecha_hora\",\n",
    "                \"nivel\",\n",
    "                \"proceso\",\n",
    "                \"archivo\",\n",
    "                \"accion\",\n",
    "                \"estado\",\n",
    "                \"detalle\"\n",
    "            ])\n",
    "\n",
    "        writer.writerow([\n",
    "            datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "            nivel,\n",
    "            proceso,\n",
    "            archivo,\n",
    "            accion,\n",
    "            estado,\n",
    "            detalle\n",
    "        ])\n",
    "\n",
    "def obtener_nombre_unico(destino: Path) -> Path:\n",
    "    if not destino.exists():\n",
    "        return destino\n",
    "\n",
    "    timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "    nuevo_nombre = f\"{destino.stem}_{timestamp}{destino.suffix}\"\n",
    "    return destino.with_name(nuevo_nombre)\n",
    "\n",
    "def mover_archivos():\n",
    "    archivos = list(LANDING_DIR.iterdir())\n",
    "\n",
    "    if not archivos:\n",
    "        escribir_log(\n",
    "            \"INFO\",\n",
    "            \"INGESTA_RAW\",\n",
    "            \"-\",\n",
    "            \"Revisión de Landing\",\n",
    "            \"Éxito\",\n",
    "            \"No se encontraron archivos para procesar\"\n",
    "        )\n",
    "        print(\"No hay archivos en Landing.\")\n",
    "        return\n",
    "\n",
    "    for archivo in archivos:\n",
    "        if archivo.is_dir():\n",
    "            continue\n",
    "\n",
    "        extension = archivo.suffix.lower()\n",
    "\n",
    "        try:\n",
    "            if extension == \".csv\":\n",
    "                destino = obtener_nombre_unico(RAW_CSV_DIR / archivo.name)\n",
    "                shutil.move(str(archivo), str(destino))\n",
    "                escribir_log(\n",
    "                    \"INFO\",\n",
    "                    \"INGESTA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Movido a raw/csv\",\n",
    "                    \"Éxito\",\n",
    "                    f\"Destino final: {destino.name}\"\n",
    "                )\n",
    "\n",
    "            elif extension in [\".xlsx\", \".xls\"]:\n",
    "                destino = obtener_nombre_unico(RAW_EXCEL_DIR / archivo.name)\n",
    "                shutil.move(str(archivo), str(destino))\n",
    "                escribir_log(\n",
    "                    \"INFO\",\n",
    "                    \"INGESTA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Movido a raw/excel\",\n",
    "                    \"Éxito\",\n",
    "                    f\"Destino final: {destino.name}\"\n",
    "                )\n",
    "\n",
    "            elif extension == \".json\":\n",
    "                destino = obtener_nombre_unico(RAW_JSON_DIR / archivo.name)\n",
    "                shutil.move(str(archivo), str(destino))\n",
    "                escribir_log(\n",
    "                    \"INFO\",\n",
    "                    \"INGESTA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Movido a raw/json\",\n",
    "                    \"Éxito\",\n",
    "                    f\"Destino final: {destino.name}\"\n",
    "                )\n",
    "\n",
    "            else:\n",
    "                destino = obtener_nombre_unico(REJECTED_DIR / archivo.name)\n",
    "                shutil.move(str(archivo), str(destino))\n",
    "                escribir_log(\n",
    "                    \"WARNING\",\n",
    "                    \"INGESTA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Formato no permitido; movido a rejected\",\n",
    "                    \"Éxito\",\n",
    "                    f\"Extensión detectada: {extension if extension else 'sin extensión'}\"\n",
    "                )\n",
    "\n",
    "        except Exception as e:\n",
    "            escribir_log(\n",
    "                \"ERROR\",\n",
    "                \"INGESTA_RAW\",\n",
    "                archivo.name,\n",
    "                \"Error durante la ingesta\",\n",
    "                \"Error\",\n",
    "                str(e)\n",
    "            )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    mover_archivos()\n",
    "    print(\"Proceso de ingesta finalizado.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9f1e150-2047-40a8-8e25-f7bc56b77106",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
