{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7b691cbf-dda5-429b-88d9-eeb2fe5a8847",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Proceso de limpieza finalizado.\n"
     ]
    }
   ],
   "source": [
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "import pandas as pd\n",
    "import shutil\n",
    "import csv\n",
    "import json\n",
    "\n",
    "BASE_DIR = Path(__file__).resolve().parent.parent\n",
    "\n",
    "DATALAKE_DIR = BASE_DIR / \"DataLake\"\n",
    "RAW_CSV_DIR = DATALAKE_DIR / \"raw\" / \"csv\"\n",
    "RAW_EXCEL_DIR = DATALAKE_DIR / \"raw\" / \"excel\"\n",
    "RAW_JSON_DIR = DATALAKE_DIR / \"raw\" / \"json\"\n",
    "SILVER_DIR = DATALAKE_DIR / \"silver\"\n",
    "REJECTED_DIR = DATALAKE_DIR / \"rejected\"\n",
    "LOGS_DIR = BASE_DIR / \"logs\"\n",
    "LOG_FILE = LOGS_DIR / \"datalake_log.csv\"\n",
    "\n",
    "def escribir_log(nivel, proceso, archivo, accion, estado, detalle):\n",
    "    existe = LOG_FILE.exists()\n",
    "\n",
    "    with open(LOG_FILE, mode=\"a\", newline=\"\", encoding=\"utf-8-sig\") as f:\n",
    "        writer = csv.writer(f)\n",
    "\n",
    "        if not existe:\n",
    "            writer.writerow([\n",
    "                \"fecha_hora\",\n",
    "                \"nivel\",\n",
    "                \"proceso\",\n",
    "                \"archivo\",\n",
    "                \"accion\",\n",
    "                \"estado\",\n",
    "                \"detalle\"\n",
    "            ])\n",
    "\n",
    "        writer.writerow([\n",
    "            datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "            nivel,\n",
    "            proceso,\n",
    "            archivo,\n",
    "            accion,\n",
    "            estado,\n",
    "            detalle\n",
    "        ])\n",
    "\n",
    "def normalizar_columnas(df):\n",
    "    df.columns = (\n",
    "        df.columns.astype(str)\n",
    "        .str.strip()\n",
    "        .str.lower()\n",
    "        .str.replace(\" \", \"_\", regex=False)\n",
    "    )\n",
    "    return df\n",
    "\n",
    "def limpiar_texto(df):\n",
    "    for col in df.select_dtypes(include=\"object\").columns:\n",
    "        df[col] = df[col].astype(str).str.strip()\n",
    "    return df\n",
    "\n",
    "def limpiar_dataframe(df):\n",
    "    filas_iniciales = len(df)\n",
    "\n",
    "    df = df.dropna(how=\"all\")\n",
    "    filas_sin_vacias = len(df)\n",
    "\n",
    "    df = normalizar_columnas(df)\n",
    "    df = limpiar_texto(df)\n",
    "\n",
    "    antes_duplicados = len(df)\n",
    "    df = df.drop_duplicates()\n",
    "    duplicados_eliminados = antes_duplicados - len(df)\n",
    "\n",
    "    detalle = (\n",
    "        f\"Filas iniciales: {filas_iniciales}, \"\n",
    "        f\"sin vacías: {filas_sin_vacias}, \"\n",
    "        f\"duplicados eliminados: {duplicados_eliminados}, \"\n",
    "        f\"filas finales: {len(df)}\"\n",
    "    )\n",
    "\n",
    "    return df, detalle\n",
    "\n",
    "def nombre_salida(nombre_archivo):\n",
    "    timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "    return f\"{Path(nombre_archivo).stem}_clean_{timestamp}.csv\"\n",
    "\n",
    "def procesar_csv():\n",
    "    for archivo in RAW_CSV_DIR.glob(\"*.csv\"):\n",
    "        try:\n",
    "            df = pd.read_csv(archivo)\n",
    "\n",
    "            if df.empty:\n",
    "                raise ValueError(\"Archivo CSV vacío o sin datos válidos\")\n",
    "\n",
    "            df_limpio, detalle = limpiar_dataframe(df)\n",
    "\n",
    "            salida = SILVER_DIR / nombre_salida(archivo.name)\n",
    "            df_limpio.to_csv(salida, index=False, encoding=\"utf-8\")\n",
    "\n",
    "            archivo.unlink()\n",
    "\n",
    "            escribir_log(\n",
    "                \"INFO\",\n",
    "                \"LIMPIEZA_RAW\",\n",
    "                archivo.name,\n",
    "                \"CSV limpiado y eliminado de raw\",\n",
    "                \"Éxito\",\n",
    "                detalle\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "            try:\n",
    "                destino = REJECTED_DIR / archivo.name\n",
    "                shutil.move(str(archivo), str(destino))\n",
    "                escribir_log(\n",
    "                    \"ERROR\",\n",
    "                    \"LIMPIEZA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Error procesando CSV; movido a rejected\",\n",
    "                    \"Error\",\n",
    "                    str(e)\n",
    "                )\n",
    "            except Exception as move_error:\n",
    "                escribir_log(\n",
    "                    \"ERROR\",\n",
    "                    \"LIMPIEZA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Error doble en CSV\",\n",
    "                    \"Error\",\n",
    "                    f\"Procesamiento: {e} | Movimiento a rejected: {move_error}\"\n",
    "                )\n",
    "\n",
    "def procesar_excel():\n",
    "    archivos_excel = list(RAW_EXCEL_DIR.glob(\"*.xlsx\")) + list(RAW_EXCEL_DIR.glob(\"*.xls\"))\n",
    "\n",
    "    for archivo in archivos_excel:\n",
    "        try:\n",
    "            df = pd.read_excel(archivo)\n",
    "\n",
    "            if df.empty:\n",
    "                raise ValueError(\"Archivo Excel vacío o sin datos válidos\")\n",
    "\n",
    "            df_limpio, detalle = limpiar_dataframe(df)\n",
    "\n",
    "            salida = SILVER_DIR / nombre_salida(archivo.name)\n",
    "            df_limpio.to_csv(salida, index=False, encoding=\"utf-8\")\n",
    "\n",
    "            archivo.unlink()\n",
    "\n",
    "            escribir_log(\n",
    "                \"INFO\",\n",
    "                \"LIMPIEZA_RAW\",\n",
    "                archivo.name,\n",
    "                \"Excel limpiado y eliminado de raw\",\n",
    "                \"Éxito\",\n",
    "                detalle\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "            try:\n",
    "                destino = REJECTED_DIR / archivo.name\n",
    "                shutil.move(str(archivo), str(destino))\n",
    "                escribir_log(\n",
    "                    \"ERROR\",\n",
    "                    \"LIMPIEZA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Error procesando Excel; movido a rejected\",\n",
    "                    \"Error\",\n",
    "                    str(e)\n",
    "                )\n",
    "            except Exception as move_error:\n",
    "                escribir_log(\n",
    "                    \"ERROR\",\n",
    "                    \"LIMPIEZA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Error doble en Excel\",\n",
    "                    \"Error\",\n",
    "                    f\"Procesamiento: {e} | Movimiento a rejected: {move_error}\"\n",
    "                )\n",
    "\n",
    "def procesar_json():\n",
    "    for archivo in RAW_JSON_DIR.glob(\"*.json\"):\n",
    "        try:\n",
    "            with open(archivo, \"r\", encoding=\"utf-8\") as f:\n",
    "                data = json.load(f)\n",
    "\n",
    "            if isinstance(data, dict):\n",
    "                df = pd.json_normalize(data)\n",
    "            elif isinstance(data, list):\n",
    "                df = pd.DataFrame(data)\n",
    "            else:\n",
    "                raise ValueError(\"Estructura JSON no soportada\")\n",
    "\n",
    "            if df.empty:\n",
    "                raise ValueError(\"Archivo JSON vacío o sin datos válidos\")\n",
    "\n",
    "            df_limpio, detalle = limpiar_dataframe(df)\n",
    "\n",
    "            salida = SILVER_DIR / nombre_salida(archivo.name)\n",
    "            df_limpio.to_csv(salida, index=False, encoding=\"utf-8\")\n",
    "\n",
    "            archivo.unlink()\n",
    "\n",
    "            escribir_log(\n",
    "                \"INFO\",\n",
    "                \"LIMPIEZA_RAW\",\n",
    "                archivo.name,\n",
    "                \"JSON limpiado y eliminado de raw\",\n",
    "                \"Éxito\",\n",
    "                detalle\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "            try:\n",
    "                destino = REJECTED_DIR / archivo.name\n",
    "                shutil.move(str(archivo), str(destino))\n",
    "                escribir_log(\n",
    "                    \"ERROR\",\n",
    "                    \"LIMPIEZA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Error procesando JSON; movido a rejected\",\n",
    "                    \"Error\",\n",
    "                    str(e)\n",
    "                )\n",
    "            except Exception as move_error:\n",
    "                escribir_log(\n",
    "                    \"ERROR\",\n",
    "                    \"LIMPIEZA_RAW\",\n",
    "                    archivo.name,\n",
    "                    \"Error doble en JSON\",\n",
    "                    \"Error\",\n",
    "                    f\"Procesamiento: {e} | Movimiento a rejected: {move_error}\"\n",
    "                )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    procesar_csv()\n",
    "    procesar_excel()\n",
    "    procesar_json()\n",
    "    print(\"Proceso de limpieza finalizado.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df5105b5-d933-45b1-9042-a134dcf1181d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
